### ISSUE TITLE
Broken latest wordpress latest gravity. 

### ISSUE THREAD

**Issue by rgfx** [ionata/Gravity-Forms-Image-Select-Field#1]
Maybe am doing something wrong...

![broken](https://user-images.githubusercontent.com/2388078/30517511-1b507f44-9b1f-11e7-9b05-4af3a720d92b.jpg)

**Comment by avioli** [comment]
Just tested with latest WordPress 4.8.2 and then again with latest Gravity Forms 2.2.5.5.

The field works as expected - installing, adding, submitting, reviewing and CSV exporting.

Keep in mind this is a field for (front-end) form submission image selection, not (back-end) field image selection. The "Select image" button is only enabled on the front-end.

The broken image in your preview is because I used `<img src="" />`. I've pushed an update to use `<img src="//:0" />` which should remove the broken icon.

**Comment by rgfx** [comment]
My issue is the inability to click select image as its greyed out. 

![questionablemasculineindianjackal-size_restricted](https://user-images.githubusercontent.com/2388078/30895207-f21fe206-a305-11e7-8e71-55e26fa8b1f1.gif)

**Comment by avioli** [comment]
As I said in my previous comment:
> Keep in mind this is a field for (front-end) form submission image selection, not (back-end) field image selection. The "Select image" button is only enabled on the front-end.

Gravity Form Fields have a "preview" area below the metabox'es header bar and above the General, Appearance, etc tabs. You are NOT meant to click Select image within the back-end.

This is a front-end ONLY field:

1. Make a page.
2. Include the form.
3. Ensure there are images in your media library.
4. Load the page.
5. Select an image.
6. Optionally crop it.
7. Optionally preview it.
8. Submit the form.
9. Review the newly submitted form entry.

I'll add this to the README.

**Comment by rgfx** [comment]
Sorry pay, I misunderstood. Thanks for your patience.
